variables:
  PROJECT_NAME: phoenix
stages:
  - build
  - test
  - deploy
before_script:
  - source ~/virtualenvs/$PROJECT_NAME/bin/activate
submit-jobs:
  stage: build
  script:
    - . /etc/profile.d/profile.modules
    - module load anaconda samtools/1.3 bwa/0.7.13 jdk picard-tools gatk
    - PYTHONPATH=.$PYTHONPATH scripts/phenix.py prepare_reference --mapper bwa --variant gatk -r test/scripts/data/reference.fa
    - PYTHONPATH=.$PYTHONPATH scripts/phenix.py prepare_reference --mapper bowtie2 --variant mpileup -r test/scripts/data/reference.fa
python-tests:
  stage: test
  script:
    - nosetests --with-coverage --cover-html --cover-package=phe test
    - if [ $? -eq 0 ]; then grep pc_cov cover/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}' ; else exit 1; fi 
  only:
    - master