variables:
  PROJECT_NAME: phoenix
stages:
  - build
  - test
  - deploy
before_script:
  - source ~/virtualenvs/P$ROJECT_NAME/bin/activate
python-tests:
  stage: test
  script:
    - env
    - nosetests --with-coverage --cover-html --cover-package=phe test
  only:
    - master