stages:
  - build
  - test
  - deploy
before_script:
  - source ~/envs/phoenix/bin/activate
job1:
  stage: test
  script:
    - env
    - nosetests --with-coverage --cover-html --cover-package=phe test
  only:
    - master